// Product master record. This is the anchor entity that Artwork, Label
// Versions, Comparison, Approvals, QA Verification and Reports will all
// reference by `id` in later modules, so its shape should stay stable.

export type ProductStatus = 'Active' | 'On Hold' | 'Pending QA' | 'Pending Approval' | 'Inactive';

export const PRODUCT_STATUS_OPTIONS: ProductStatus[] = ['Active', 'On Hold', 'Pending QA', 'Pending Approval', 'Inactive'];

// How this record came to exist. Manual "Add Product" no longer exists in
// the UI (see ProductsPage) — every new product is now generated by the
// label upload pipeline (services/labelIntakeService.ts). 'origin' is
// undefined on every record seeded/created before this feature, which
// ProductsPage displays as a legacy manual entry rather than guessing.
export type ProductOrigin = 'Label Upload' | 'Manual Entry';

export type Product = {
  id: string; // e.g. PRD-0001, stable for life of the record
  productName: string;
  brandName: string;
  marketingCompany: string;
  manufacturingCompany: string;
  flavour: string;
  fssaiNumber: string;
  // Net content / count printed on the front of the label (e.g. "60
  // Gummies", "150 g"). Optional since it predates existing Product
  // Management records (see data/products.ts) — the label upload pipeline
  // (labelIntakeService.ts) always requires it for new intake.
  packageSize?: string;
  status: ProductStatus;
  createdDate: string;
  updatedDate: string;
  createdBy: string;
  updatedBy: string;
  origin?: ProductOrigin;
  // The artwork whose label upload created this product, when origin is
  // 'Label Upload' — lets Product Management show where the record came
  // from (see ProductsPage's Product Details drawer).
  sourceArtworkId?: string;
};

// Editable fields only — id and audit fields are managed by the service.
export type ProductInput = {
  productName: string;
  brandName: string;
  marketingCompany: string;
  manufacturingCompany: string;
  flavour: string;
  fssaiNumber: string;
  packageSize?: string;
  status: ProductStatus;
};
