import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Alert, Box, Button, Card, Paper, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, Typography } from '@mui/material';
import { MdArrowForward, MdCancel, MdCheckCircle, MdWarningAmber } from 'react-icons/md';
import { PageHeader } from '../components/PageHeader';
import { StatCard, DashboardStatCard } from '../components/StatCard';
import { StatusChip } from '../components/StatusChip';
import { useAuth } from '../auth/AuthContext';
import { ActionId, RoleId } from '../auth/permissions';
import { getFinalApprovedArtworks } from '../services/artworkService';
import {
  getDashboardSummary,
  getMyPendingWork,
  getRecentActivity,
  getUnsubmittedComparisons,
  DashboardSummary,
  RecentActivityItem
} from '../services/comparisonService';
import { Comparison } from '../types/comparison';
import { formatDateTime } from '../utils/dateFormat';

// -------------------------------------------------------------------------
// Role-specific "My Pending Work" queue + Quick Actions. Every queue here
// comes straight from an existing comparisonService getter â€” Dashboard.tsx
// only picks which one to call for the current role, it never filters raw
// records itself. Every action just navigates to an existing protected
// route; the Dashboard never performs an approval action directly.
// -------------------------------------------------------------------------

type PendingWorkConfig = { heading: string; actionLabel: string; route: string };

const PENDING_WORK_CONFIG: Record<RoleId, PendingWorkConfig> = {
  label_final: { heading: 'Pending Label Final Review', actionLabel: 'Review', route: '/approvals' },
  technical: { heading: 'Pending Technical Verification', actionLabel: 'Verify', route: '/approvals' },
  qa: { heading: 'Pending QA Verification', actionLabel: 'Review', route: '/qa' },
  manager: { heading: 'Pending Manager Approval', actionLabel: 'Approve', route: '/approvals' },
  account_manager: { heading: 'Comparisons Ready to Submit', actionLabel: 'Submit', route: '/comparison' }
};

// Assignment-aware: getMyPendingWork already restricts a role's four
// approval stages to unassigned-or-assigned-to-me items (see
// comparisonService). Account Manager has no assignable stage â€” their
// "pending work" is comparisons they haven't submitted yet.
function getPendingWorkForRole(role: RoleId, userId: string): Comparison[] {
  if (role === 'account_manager') return getUnsubmittedComparisons();
  return getMyPendingWork(userId, role);
}

type QuickAction = { label: string; route: string; action: ActionId };

// "Add Product" was removed â€” products are now generated by uploading a
// label's artwork (see ArtworkPage / labelIntakeService), so "Upload
// Artwork" below is the entry point for creating a product too.
const QUICK_ACTIONS: Record<RoleId, QuickAction[]> = {
  manager: [
    { label: 'Upload Artwork', route: '/artwork', action: 'UPLOAD' },
    { label: 'Manage Users', route: '/users', action: 'MANAGE_USERS' }
  ],
  label_final: [{ label: 'Review Labels', route: '/approvals', action: 'REVIEW' }],
  technical: [{ label: 'Technical Verification', route: '/approvals', action: 'REVIEW' }],
  qa: [{ label: 'QA Verification', route: '/qa', action: 'VERIFY' }],
  account_manager: [
    { label: 'Upload Artwork', route: '/artwork', action: 'UPLOAD' },
    { label: 'Compare Labels', route: '/comparison', action: 'COMPARE' }
  ]
};

function activityLabel(item: RecentActivityItem): string {
  switch (item.action) {
    case 'Sent to Technical':
      return 'Label Final Approved';
    case 'Sent to QA':
      return 'Technical Verification Approved';
    case 'Sent to Manager':
      return 'QA Verification Completed';
    case 'Final Approved':
      return 'Final Approved';
    case 'Rejected':
      return 'Rejected';
    case 'Revision Requested':
      return `${item.stage} Sent Back for Revision`;
    default:
      return item.action;
  }
}

function activityIcon(item: RecentActivityItem) {
  if (item.action === 'Rejected') return <MdCancel color="var(--c-error)" size={20} />;
  if (item.action === 'Revision Requested') return <MdWarningAmber color="var(--c-warn-400)" size={20} />;
  return <MdCheckCircle color="var(--c-green)" size={20} />;
}

type DashboardData = {
  summary: DashboardSummary;
  finalApprovedArtworks: ReturnType<typeof getFinalApprovedArtworks>;
  recentActivity: RecentActivityItem[];
  unsubmittedCount: number;
  pendingWork: Comparison[];
};

function loadDashboardData(role: RoleId, userId: string): DashboardData {
  return {
    summary: getDashboardSummary(),
    finalApprovedArtworks: getFinalApprovedArtworks(),
    recentActivity: getRecentActivity(8),
    unsubmittedCount: getUnsubmittedComparisons().length,
    pendingWork: getPendingWorkForRole(role, userId)
  };
}

export function DashboardPage() {
  const navigate = useNavigate();
  const { currentUser, hasPermission } = useAuth();
  const role: RoleId = currentUser?.role ?? 'account_manager';
  const userId = currentUser?.id ?? '';

  const [data] = useState<DashboardData | null>(() => {
    try {
      return loadDashboardData(role, userId);
    } catch {
      return null;
    }
  });

  if (!data) {
    return (
      <Box>
        <PageHeader title="Dashboard" subtitle="Live overview of products, artwork, and the approval workflow." />
        <Alert severity="error">Something went wrong loading the dashboard. Please refresh the page.</Alert>
      </Box>
    );
  }

  const { summary, finalApprovedArtworks, recentActivity, unsubmittedCount, pendingWork } = data;
  const pendingConfig = PENDING_WORK_CONFIG[role];
  const quickActions = (QUICK_ACTIONS[role] ?? []).filter((action) => hasPermission(action.action));

  const statCards: Array<DashboardStatCard & { route?: string }> = [
    { title: 'Total Products', value: summary.totalProducts, icon: 'MdInventory2', color: 'var(--c-orange)', route: '/products' },
    { title: 'Total Artwork', value: summary.totalArtwork, icon: 'MdBrush', color: 'var(--c-green)', route: '/artwork' },
    { title: 'Pending Comparison', value: summary.pendingComparison, icon: 'MdCompareArrows', color: 'var(--c-info)', route: '/artwork' },
    { title: 'Pending Approval', value: summary.pendingApproval, icon: 'MdVerified', color: 'var(--c-orange-500)', route: '/approvals' },
    { title: 'Final Approved', value: summary.finalApproved, icon: 'MdCheckCircleOutline', color: 'var(--c-green)', route: '/artwork' },
    { title: 'Revision Required', value: summary.revisionRequired, icon: 'MdErrorOutline', color: 'var(--c-error)', route: '/approvals' }
  ];

  const workflowStages = [
    { label: 'Artwork', count: summary.pendingComparison },
    { label: 'Comparison', count: unsubmittedCount },
    { label: 'Label Final', count: summary.pendingLabelFinal },
    { label: 'Technical', count: summary.pendingTechnical },
    { label: 'QA', count: summary.pendingQA },
    { label: 'Manager', count: summary.pendingManagerApproval },
    { label: 'Final Approved', count: summary.finalApproved }
  ];

  const approvalStageCards = [
    { label: 'Label Final', count: summary.pendingLabelFinal },
    { label: 'Technical', count: summary.pendingTechnical },
    { label: 'QA', count: summary.pendingQA },
    { label: 'Manager Approval', count: summary.pendingManagerApproval }
  ];

  return (
    <Box sx={{ display: 'grid', gap: 3 }}>
      <PageHeader title="Dashboard" subtitle="Live overview of products, artwork, and the approval workflow." />

      {/* Top statistics */}
      <Box sx={{ display: 'grid', gap: 3, gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))' }}>
        {statCards.map((card) => (
          <StatCard key={card.title} card={card} onClick={card.route ? () => navigate(card.route!) : undefined} />
        ))}
      </Box>

      {/* My Pending Work â€” role-specific, shown prominently right under the top stats */}
      <Paper sx={{ p: 3, borderRadius: 4, border: '1px solid rgba(0,166,81,0.2)' }}>
        <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 2, flexWrap: 'wrap', gap: 1 }}>
          <Typography variant="h6" sx={{ fontWeight: 700 }}>
            My Pending Work
          </Typography>
          <Typography variant="body2" sx={{ color: 'var(--c-text-3)' }}>
            {pendingConfig.heading}
          </Typography>
        </Box>
        {pendingWork.length === 0 ? (
          <Typography variant="body2" sx={{ color: 'var(--c-text-3)', py: 3, textAlign: 'center' }}>
            No pending work for your role right now.
          </Typography>
        ) : (
          <Box sx={{ display: 'grid', gap: 1.5 }}>
            {pendingWork.slice(0, 5).map((item) => (
              <Box
                key={item.id}
                sx={{
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'space-between',
                  flexWrap: 'wrap',
                  gap: 1,
                  p: 2,
                  borderRadius: 3,
                  bgcolor: 'var(--c-surface)'
                }}
              >
                <Box>
                  <Typography variant="body2" sx={{ fontWeight: 700 }}>
                    {item.id} â€” {item.productName}
                  </Typography>
                  <Box sx={{ mt: 0.5 }}>
                    <StatusChip status={item.status} />
                  </Box>
                </Box>
                <Button
                  variant="contained"
                  size="small"
                  onClick={() => navigate(pendingConfig.route)}
                  sx={{ textTransform: 'none', bgcolor: 'var(--c-info)', '&:hover': { bgcolor: 'var(--c-info-700)' } }}
                >
                  {pendingConfig.actionLabel}
                </Button>
              </Box>
            ))}
          </Box>
        )}
      </Paper>

      {/* Approval Workflow summary */}
      <Box>
        <Typography variant="h6" sx={{ fontWeight: 700, mb: 2 }}>
          Approval Workflow
        </Typography>
        <Box sx={{ display: 'grid', gap: 2, gridTemplateColumns: { xs: '1fr', sm: 'repeat(2, 1fr)', md: 'repeat(4, 1fr)' } }}>
          {approvalStageCards.map((stage) => (
            <Card key={stage.label} sx={{ p: 3, borderRadius: 3, bgcolor: 'var(--c-surface)' }}>
              <Typography variant="subtitle2" sx={{ color: 'var(--c-text-2)', mb: 1, fontWeight: 700 }}>
                {stage.label}
              </Typography>
              <Typography variant="h4" sx={{ fontWeight: 800 }}>
                {stage.count}
              </Typography>
              <Typography variant="body2" sx={{ color: 'var(--c-text-3)' }}>
                Pending
              </Typography>
            </Card>
          ))}
        </Box>
      </Box>

      {/* Workflow status visualization */}
      <Paper sx={{ p: 3, borderRadius: 4 }}>
        <Typography variant="h6" sx={{ fontWeight: 700, mb: 3 }}>
          Workflow Status
        </Typography>
        <Box sx={{ display: 'flex', alignItems: 'center', flexWrap: 'wrap', gap: 1.5 }}>
          {workflowStages.map((stage, index) => (
            <Box key={stage.label} sx={{ display: 'flex', alignItems: 'center', gap: 1.5 }}>
              <Box
                sx={{
                  textAlign: 'center',
                  px: 2.5,
                  py: 1.5,
                  borderRadius: 3,
                  minWidth: 96,
                  bgcolor: index === workflowStages.length - 1 ? 'rgba(0,166,81,0.1)' : 'var(--c-surface)',
                  border: index === workflowStages.length - 1 ? '1px solid rgba(0,166,81,0.3)' : '1px solid transparent'
                }}
              >
                <Typography variant="h6" sx={{ fontWeight: 800, color: index === workflowStages.length - 1 ? 'var(--c-green)' : 'var(--c-text-1)' }}>
                  {stage.count}
                </Typography>
                <Typography variant="caption" sx={{ color: 'var(--c-text-3)', fontWeight: 700 }}>
                  {stage.label}
                </Typography>
              </Box>
              {index < workflowStages.length - 1 && <MdArrowForward color="var(--c-border)" size={20} />}
            </Box>
          ))}
        </Box>
      </Paper>

      {/* Final Approved Labels + Revision/Rejected summary */}
      <Box sx={{ display: 'grid', gap: 3, gridTemplateColumns: { xs: '1fr', lg: '2fr 1fr' } }}>
        <Paper sx={{ p: 3, borderRadius: 4 }}>
          <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 2 }}>
            <Typography variant="h6" sx={{ fontWeight: 700 }}>
              Final Approved Labels
            </Typography>
            <Button size="small" sx={{ textTransform: 'none', color: 'var(--c-info)' }} onClick={() => navigate('/artwork')}>
              View All
            </Button>
          </Box>
          {finalApprovedArtworks.length === 0 ? (
            <Typography variant="body2" sx={{ color: 'var(--c-text-3)', py: 3, textAlign: 'center' }}>
              No labels have been finally approved yet.
            </Typography>
          ) : (
            <TableContainer>
              <Table size="small">
                <TableHead>
                  <TableRow>
                    <TableCell sx={{ fontWeight: 700 }}>Product Name</TableCell>
                    <TableCell sx={{ fontWeight: 700 }}>Brand</TableCell>
                    <TableCell sx={{ fontWeight: 700 }}>Version</TableCell>
                    <TableCell sx={{ fontWeight: 700 }}>Party</TableCell>
                    <TableCell sx={{ fontWeight: 700 }}>Approved Date</TableCell>
                    <TableCell sx={{ fontWeight: 700 }}>Approved By</TableCell>
                    <TableCell sx={{ fontWeight: 700 }}>Status</TableCell>
                  </TableRow>
                </TableHead>
                <TableBody>
                  {finalApprovedArtworks.slice(0, 5).map((artwork) => (
                    <TableRow key={artwork.id} hover sx={{ '&:hover': { bgcolor: 'var(--c-tint-orange)' } }}>
                      <TableCell>{artwork.productName}</TableCell>
                      <TableCell>{artwork.brand}</TableCell>
                      <TableCell>{artwork.version}</TableCell>
                      <TableCell>{artwork.marketingCompany}</TableCell>
                      <TableCell>{formatDateTime(artwork.updatedDate)}</TableCell>
                      <TableCell>{artwork.updatedBy}</TableCell>
                      <TableCell>
                        <StatusChip status={artwork.status} />
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </TableContainer>
          )}
        </Paper>

        <Paper sx={{ p: 3, borderRadius: 4 }}>
          <Typography variant="h6" sx={{ fontWeight: 700, mb: 2 }}>
            Needs Attention
          </Typography>
          <Box
            sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', p: 2, borderRadius: 3, bgcolor: 'var(--c-tint-warn)', mb: 1.5, cursor: 'pointer' }}
            onClick={() => navigate('/approvals')}
          >
            <Typography variant="body2" sx={{ fontWeight: 700, color: 'var(--c-warn-800)' }}>
              Revision Required
            </Typography>
            <Typography variant="h5" sx={{ fontWeight: 800, color: 'var(--c-warn-800)' }}>
              {summary.revisionRequired}
            </Typography>
          </Box>
          <Box
            sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', p: 2, borderRadius: 3, bgcolor: 'var(--c-tint-error-2)', cursor: 'pointer' }}
            onClick={() => navigate('/approvals')}
          >
            <Typography variant="body2" sx={{ fontWeight: 700, color: 'var(--c-error)' }}>
              Rejected
            </Typography>
            <Typography variant="h5" sx={{ fontWeight: 800, color: 'var(--c-error)' }}>
              {summary.rejected}
            </Typography>
          </Box>
        </Paper>
      </Box>

      {/* Recent Activity + Quick Actions */}
      <Box sx={{ display: 'grid', gap: 3, gridTemplateColumns: { xs: '1fr', lg: '2fr 1fr' } }}>
        <Paper sx={{ p: 3, borderRadius: 4 }}>
          <Typography variant="h6" sx={{ fontWeight: 700, mb: 2 }}>
            Recent Activity
          </Typography>
          {recentActivity.length === 0 ? (
            <Typography variant="body2" sx={{ color: 'var(--c-text-3)', py: 3, textAlign: 'center' }}>
              No recent activity.
            </Typography>
          ) : (
            <Box sx={{ display: 'grid', gap: 1.5 }}>
              {recentActivity.map((item, index) => (
                <Box
                  key={`${item.comparisonId}-${item.date}-${index}`}
                  sx={{ display: 'flex', alignItems: 'flex-start', gap: 1.5, p: 2, borderRadius: 3, bgcolor: 'var(--c-surface)' }}
                >
                  {activityIcon(item)}
                  <Box sx={{ flex: 1 }}>
                    <Typography variant="body2" sx={{ fontWeight: 700 }}>
                      {activityLabel(item)}
                    </Typography>
                    <Typography variant="body2" sx={{ color: 'var(--c-text-3)' }}>
                      {item.comparisonId} â€¢ {item.productName}
                    </Typography>
                    <Typography variant="caption" sx={{ color: 'var(--c-text-3)' }}>
                      {item.actorName} Â· {formatDateTime(item.date)}
                    </Typography>
                  </Box>
                  <StatusChip status={item.status} />
                </Box>
              ))}
            </Box>
          )}
        </Paper>

        <Paper sx={{ p: 3, borderRadius: 4 }}>
          <Typography variant="h6" sx={{ fontWeight: 700, mb: 2 }}>
            Quick Actions
          </Typography>
          {quickActions.length === 0 ? (
            <Typography variant="body2" sx={{ color: 'var(--c-text-3)' }}>
              No quick actions available for your role.
            </Typography>
          ) : (
            quickActions.map((action, index) => (
              <Button
                key={action.label}
                fullWidth
                variant={index === 0 ? 'contained' : 'outlined'}
                onClick={() => navigate(action.route)}
                sx={
                  index === 0
                    ? { mb: 2, bgcolor: 'var(--c-orange)', '&:hover': { bgcolor: 'var(--c-orange-600)' }, textTransform: 'none' }
                    : { mb: 2, borderColor: 'var(--c-green)', color: 'var(--c-text-1)', textTransform: 'none' }
                }
              >
                {action.label}
              </Button>
            ))
          )}
        </Paper>
      </Box>
    </Box>
  );
}
